/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Estructuras.ArbolAVL;
import Estructuras.NodoArbol;
import Modelo.Boleta;
import Sistema.OlvaCourier;
import java.awt.Graphics;

/**
 *
 * @author Alex
 */
public class FrmArbolLienzo extends javax.swing.JFrame {

    private ArbolAVL arbolito= new ArbolAVL();
    public static final int DIAMETRO = 30;
    public static final int RADIO = DIAMETRO / 2;
    public static final int ANCHO = 50;
    public static int opc;
    
    public FrmArbolLienzo(int opc) {
        initComponents();
        this.opc=opc;
        arbolito.creacionArbolXLista(OlvaCourier.clienteActual.getListaBoletas(), opc);
        setLocationRelativeTo(null);
        setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(botonSalir)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(517, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmArbolLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmArbolLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmArbolLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmArbolLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmArbolLienzo(opc).setVisible(true);
            }
        });
    }
    private void pintar(Graphics g, int x, int y, NodoArbol n) {
        if (n == null)
        {}
        else {
            int EXTRA = n.nodosCompletos(n) * (ANCHO / 2);
            g.drawOval(x, y, DIAMETRO, DIAMETRO);
            Boleta miBoleta = (Boleta) n.getObjeto();
            switch(opc){
                case 0: g.drawString(String.valueOf(miBoleta.getCodigoBoleta()), x + 12, y + 18);break; 
                case 1: g.drawString(String.valueOf(miBoleta.getAgenciaInicial().getNumero()+" "+miBoleta.getAgenciaInicial().getUbicacion()), x + 12, y + 18);break;
                case 2: g.drawString(String.valueOf(miBoleta.getAgenciaFinal().getNumero()+" "+miBoleta.getAgenciaFinal().getUbicacion()), x + 12, y + 18);break;
                case 3: g.drawString(String.valueOf(miBoleta.getFechaEmision().getTime().toLocaleString()), x + 12, y + 18);break;
                case 4: g.drawString(String.valueOf(miBoleta.getFechaEmision().getTime().toLocaleString()), x + 12, y + 18);break;
                case 5: g.drawString(String.valueOf(miBoleta.getImporteTotal()), x + 12, y + 18);break;
            }
 
            if (n.getIzq() != null)
                g.drawLine(x+ RADIO, y + RADIO, x-ANCHO-EXTRA+RADIO, y+ANCHO+RADIO);
            if (n.getDer()!= null)
                g.drawLine(x+ RADIO, y + RADIO, x+ANCHO+EXTRA+RADIO, y+ANCHO+RADIO);
            
            pintar(g, x - ANCHO-EXTRA, y+ANCHO, n.getIzq());
            pintar(g, x + ANCHO+EXTRA, y+ANCHO, n.getDer());
        }
    }
    
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        NodoArbol n = arbolito.getRaiz();
        if (n == null)
        {}
        else {
            int EXTRA = n.nodosCompletos(n) * (ANCHO / 2);
            g.drawOval(this.getWidth()/2, 20, DIAMETRO, DIAMETRO);
            int x = this.getWidth()/2;
            int y=20;
            Boleta miBoleta = (Boleta) n.getObjeto();
            switch(opc){
                case 0: g.drawString(String.valueOf(miBoleta.getCodigoBoleta()), x + 12, y + 18);break; 
                case 1: g.drawString(String.valueOf(miBoleta.getAgenciaInicial().getNumero()+" "+miBoleta.getAgenciaInicial().getUbicacion()), x + 12, y + 18);break;
                case 2: g.drawString(String.valueOf(miBoleta.getAgenciaFinal().getNumero()+" "+miBoleta.getAgenciaFinal().getUbicacion()), x + 12, y + 18);break;
                case 3: g.drawString(String.valueOf(miBoleta.getFechaEmision().getTime().toLocaleString()), x + 12, y + 18);break;
                case 4: g.drawString(String.valueOf(miBoleta.getFechaEmision().getTime().toLocaleString()), x + 12, y + 18);break;
                case 5: g.drawString(String.valueOf(miBoleta.getImporteTotal()), x + 12, y + 18);break;
            }
 
            if (n.getIzq() != null)
                g.drawLine(x+ RADIO, y + RADIO, x-ANCHO-EXTRA+RADIO, y+ANCHO+RADIO);
            if (n.getDer()!= null)
                g.drawLine(x+ RADIO, y + RADIO, x+ANCHO+EXTRA+RADIO, y+ANCHO+RADIO);
            
            pintar(g, x - ANCHO-EXTRA, y+ANCHO, n.getIzq());
            pintar(g, x + ANCHO+EXTRA, y+ANCHO, n.getDer());
        }
        
        
        pintar(g, this.getWidth() / 2, 20, arbolito.getRaiz());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
